# Generated by Django 4.2.10 on 2024-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
